[package]
    name    = "custom-errors-2"
    version = "0.1.0"

    authors.workspace = true
    edition.workspace = true
    publish.workspace = true

[dependencies]
    env_logger.workspace = true
    log.workspace        = true
