[package]
    name    = "blog_api"
    version = "0.1.0"

    authors = ["Jade Lynn Masker <donottellmetonottellyou@gmail.com>"]

    edition = "2021"

[dependencies]
    blog_shared = { path = "../blog_shared" }
