[package]
    name    = "draw-consumer"
    version = "0.1.0"

    authors.workspace = true
    edition.workspace = true
    publish.workspace = true

[dependencies]
    cargo-features = { path = "../../", default-features = false, features = ["color", "shapes"] }
