[package]
    name    = "external-dependencies"
    version = "0.1.0"

    authors.workspace = true
    edition.workspace = true
    publish.workspace = true

[dependencies]
    rand.workspace = true
