[package]
    name    = "ffi-rust-from-c"
    version = "0.1.0"

    authors.workspace = true
    edition.workspace = true
    publish.workspace = true

[lib]
    crate-type = ["cdylib"]

[dependencies]
