[package]
    name    = "function-like-procedural-macros"
    version = "0.1.0"

    authors.workspace = true
    edition.workspace = true
    publish.workspace = true

[lib]
    proc-macro = true

[dependencies]
    chrono = "0.4.*"
    quote  = "1.*"
