[package]
    name    = "publishing_your_package"
    version = "0.1.0"

    authors.workspace = true
    description       = "an auth service"
    license           = "MIT"

    edition.workspace = true
    publish.workspace = true

[dependencies]
    rand.workspace = true
