[package]
    name    = "blog-api"
    version = "0.1.0"

    authors.workspace = true
    edition.workspace = true
    publish.workspace = true

[dependencies]
    blog-shared = { path = "../blog-shared" }
