[package]
    name    = "streams"
    version = "0.1.0"

    authors.workspace = true
    edition.workspace = true
    publish.workspace = true

[dependencies]
    tokio.workspace        = true
    tokio-stream.workspace = true
