[package]
    name    = "propagating-errors"
    version = "0.1.0"

    authors.workspace = true
    edition.workspace = true
    publish.workspace = true

[dependencies]
    unicode-segmentation.workspace = true
