[package]
    name    = "draw_consumer"
    version = "0.1.0"

    authors = ["Jade Lynn Masker <donottellmetonottellyou@gmail.com>"]

    edition = "2021"

[dependencies]
    cargo_features = { path = "../", default-features = false, features = [
        "color",
        "shapes",
    ] }
