[workspace]
    members  = ["blog-api", "blog-shared", "blog-web"]
    resolver = "2"

    [workspace.package]
        authors = ["Jade Lynn Masker <donottellmetonottellyou@gmail.com>"]
        edition = "2021"
        publish = false
