[package]
    name    = "draw_consumer"
    version = "0.1.0"

    authors.workspace = true
    edition.workspace = true
    publish.workspace = true

[dependencies]
    cargo_features = { path = "../", default-features = false, features = ["color", "shapes"] }
