[package]
    name    = "blog_shared"
    version = "0.1.0"

    authors.workspace = true
    edition.workspace = true
    publish.workspace = true

[dependencies]
    serde = { version = "1.0", features = ["derive"] }
